version: '3.2'
services:
  db:
    image: postgres
    ports:
      - "5432:5432"
  api:
    build: .
    volumes:
      - type: bind
        source: .
        target: /etc/dod-api
    ports:
      - "8000:8000"
    depends_on:
      - db
    command:
      - ./run.sh
